# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"\x07\n\x05\x45mpty\"\x15\n\x05\x46rame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x16\n\x03Req\x12\x0f\n\x07message\x18\x01 \x01(\x05\"\x17\n\x04Resp\x12\x0f\n\x07message\x18\x01 \x01(\x05\x32=\n\x0bVideoStream\x12.\n\x0cStreamFrames\x12\x0c.video.Empty\x1a\x0c.video.Frame\"\x00\x30\x01\x32-\n\x05Hello\x12$\n\x07\x63\x61llPrc\x12\n.video.Req\x1a\x0b.video.Resp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_FRAME']._serialized_start=31
  _globals['_FRAME']._serialized_end=52
  _globals['_REQ']._serialized_start=54
  _globals['_REQ']._serialized_end=76
  _globals['_RESP']._serialized_start=78
  _globals['_RESP']._serialized_end=101
  _globals['_VIDEOSTREAM']._serialized_start=103
  _globals['_VIDEOSTREAM']._serialized_end=164
  _globals['_HELLO']._serialized_start=166
  _globals['_HELLO']._serialized_end=211
# @@protoc_insertion_point(module_scope)
